#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
# xmodmap "/home/haruyama/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

export VTE_CJK_WIDTH=1

pkill notification-daemon
/usr/lib/notification-daemon/notification-daemon &

pkill gnome-screensaver
/usr/bin/gnome-screensaver &

pkill xautolock
/usr/bin/xautolock -locker "/usr/bin/gnome-screensaver-command -l" &

/usr/bin/fbsetroot -solid black

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/haruyama/.fluxbox/log"
