# based on http://www.clear-code.com/blog/2011/9/5.html
bindkey -e

setopt always_last_prompt
setopt auto_list auto_pushd auto_menu auto_cd auto_name_dirs auto_remove_slash auto_param_keys
setopt bang_hist
setopt cdable_vars
setopt complete_in_word
setopt correct
setopt equals
setopt extended_glob
setopt extended_history
setopt hash_cmds
setopt hist_ignore_all_dups hist_ignore_dups hist_ignore_space hist_no_store hist_expand hist_reduce_blanks
setopt ignoreeof
setopt inc_append_history
setopt list_packed list_types
setopt long_list_jobs
setopt magic_equal_subst
setopt multios
setopt no_beep
setopt no_clobber
setopt no_list_beep no_hup no_check_jobs
setopt no_flow_control no_bg_nice
setopt notify
setopt numeric_glob_sort
setopt path_dirs
setopt print_eight_bit
setopt prompt_subst prompt_percent
setopt pushd_ignore_dups pushd_to_home
setopt rc_quotes
setopt rm_star_silent
setopt share_history
setopt short_loops
setopt sh_word_split
setopt transient_rprompt
#setopt mark_dirs
#setopt glob_complete
#setopt no_unset
#setopt sun_keyboard_hack

cdpath=(~)
function chpwd_print() {
if [ x"$DISPLAY" != x"" ]; then 
        print -Pn "\e]2; [%m] : %~\a"
fi
}
typeset -ga chpwd_functions
chpwd_print
chpwd_functions+=dirs
chpwd_functions+=chpwd_print

HISTSIZE=1000000
SAVEHIST=$HISTSIZE
HISTFILE="$HOME/.zhistory"

function history-all { history -E 1 }

if type ruby > /dev/null 2>&1; then
        _cache_hosts=(`env RUBYOPT="" ruby -ne 'if /^Host\s+(.+)$/; print $1.strip, "\n"; end' ~/.ssh/config`)
fi

autoload -U compinit
compinit
zstyle ':completion:*' format '%B%d%b'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*:default' menu select=1
zstyle ':completion:*:default' list-colors ""
#zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z} r:|[._-]=*'
zstyle ':completion:*' completer _oldlist _complete _match _history _ignored _approximate _prefix
zstyle ':completion:*' use-cache yes
zstyle ':completion:*' verbose yes
#zstyle ':completion:sudo:*' environ PATH="$SUDO_PATH:$PATH"
REPORTTIME=3

WORDCHARS=${WORDCHARS:s,/,,}

alias -g L="|& $PAGER"
alias -g G='| grep -a'
alias -g H='| head'
alias -g T='| tail'
alias -g S='| sed'
alias -g W='| wc'
alias ls='ls -F --color=auto'
alias gd='dirs -v; echo -n "select number: "; read newdir; cd +"$newdir"'
alias env_EUC='env LANG=ja_JP.eucJP LC_ALL=ja_JP.eucJP'
alias env_UTF-8='env LANG=ja_JP.UTF-8 LC_ALL=ja_JP.UTF-8'
alias env_SJIS='env LANG=ja_JP.SJIS LC_ALL=ja_JP.SJIS'

export RSYNC_RSH=ssh
export SUDO_PROMPT="sudo_password: "

bindkey '^R' history-incremental-pattern-search-backward
bindkey '^S' history-incremental-pattern-search-forward

# http://qiita.com/mollifier/items/8d5a627d773758dd8078
autoload -Uz add-zsh-hook
autoload -Uz colors
colors
autoload -Uz vcs_info
autoload -Uz is-at-least

zstyle ':vcs_info:*' max-exports 3

zstyle ':vcs_info:*' enable git svn hg bzr
zstyle ':vcs_info:*' formats '(%s)-[%b]'
zstyle ':vcs_info:*' actionformats '(%s)-[%b]' '%m' '<!%a>'
zstyle ':vcs_info:(svn|bzr):*' branchformat '%b:r%r'
zstyle ':vcs_info:bzr:*' use-simple true

autoload -Uz is-at-least
if is-at-least 4.3.10; then
        zstyle ':vcs_info:git:*' formats '(%s)-[%b]' '%c%u %m'
        zstyle ':vcs_info:git:*' actionformats '(%s)-[%b]' '%c%u %m' '<!%a>'
        zstyle ':vcs_info:git:*' check-for-changes true
        zstyle ':vcs_info:git:*' stagedstr "+"    # 適当な文字列に変更する
        zstyle ':vcs_info:git:*' unstagedstr "-"  # 適当の文字列に変更する
fi
# hooks 設定
if is-at-least 4.3.11; then
        # git のときはフック関数を設定する

        # formats '(%s)-[%b]' '%c%u %m' , actionformats '(%s)-[%b]' '%c%u %m' '<!%a>'
        # のメッセージを設定する直前のフック関数
        # 今回の設定の場合はformat の時は2つ, actionformats の時は3つメッセージがあるので
        # 各関数が最大3回呼び出される。
        zstyle ':vcs_info:git+set-message:*' hooks \
                git-hook-begin \
                git-untracked \
                git-push-status \
                git-nomerge-branch \
                git-stash-count

        # フックの最初の関数
        # git の作業コピーのあるディレクトリのみフック関数を呼び出すようにする
        # (.git ディレクトリ内にいるときは呼び出さない)
        # .git ディレクトリ内では git status --porcelain などがエラーになるため
        function +vi-git-hook-begin() {
        if [[ $(command git rev-parse --is-inside-work-tree 2> /dev/null) != 'true' ]]; then
                # 0以外を返すとそれ以降のフック関数は呼び出されない
                return 1
        fi

        return 0
}

# untracked フィアル表示
#
# untracked ファイル(バージョン管理されていないファイル)がある場合は
# unstaged (%u) に ? を表示
function +vi-git-untracked() {
# zstyle formats, actionformats の2番目のメッセージのみ対象にする
if [[ "$1" != "1" ]]; then
        return 0
fi

if command git status --porcelain 2> /dev/null \
        | awk '{print $1}' \
        | command grep -F '??' > /dev/null 2>&1 ; then

# unstaged (%u) に追加
hook_com[unstaged]+='?'
        fi
}

# push していないコミットの件数表示
#
# リモートリポジトリに push していないコミットの件数を
# pN という形式で misc (%m) に表示する
function +vi-git-push-status() {
# zstyle formats, actionformats の2番目のメッセージのみ対象にする
if [[ "$1" != "1" ]]; then
        return 0
fi

if [[ "${hook_com[branch]}" != "master" ]]; then
        # master ブランチでない場合は何もしない
        return 0
fi

# push していないコミット数を取得する
local ahead
ahead=$(command git rev-list origin/master..master 2>/dev/null \
        | wc -l \
        | tr -d ' ')

if [[ "$ahead" -gt 0 ]]; then
        # misc (%m) に追加
        hook_com[misc]+="(p${ahead})"
fi
    }

    # マージしていない件数表示
    #
    # master 以外のブランチにいる場合に、
    # 現在のブランチ上でまだ master にマージしていないコミットの件数を
    # (mN) という形式で misc (%m) に表示
    function +vi-git-nomerge-branch() {
    # zstyle formats, actionformats の2番目のメッセージのみ対象にする
    if [[ "$1" != "1" ]]; then
            return 0
    fi

    if [[ "${hook_com[branch]}" == "master" ]]; then
            # master ブランチの場合は何もしない
            return 0
    fi

    local nomerged
    nomerged=$(command git rev-list master..${hook_com[branch]} 2>/dev/null | wc -l | tr -d ' ')

    if [[ "$nomerged" -gt 0 ]] ; then
            # misc (%m) に追加
            hook_com[misc]+="(m${nomerged})"
    fi
    }

    # stash 件数表示
    #
    # stash している場合は :SN という形式で misc (%m) に表示
    function +vi-git-stash-count() {
    # zstyle formats, actionformats の2番目のメッセージのみ対象にする
    if [[ "$1" != "1" ]]; then
            return 0
    fi

    local stash
    stash=$(command git stash list 2>/dev/null | wc -l | tr -d ' ')
    if [[ "${stash}" -gt 0 ]]; then
            # misc (%m) に追加
            hook_com[misc]+=":S${stash}"
    fi
    }

fi

function _update_vcs_info_msg() {
local -a messages
local prompt

LANG=en_US.UTF-8 vcs_info

if [[ -z ${vcs_info_msg_0_} ]]; then
        # vcs_info で何も取得していない場合はプロンプトを表示しない
        prompt=""
else
        # vcs_info で情報を取得した場合
        # $vcs_info_msg_0_ , $vcs_info_msg_1_ , $vcs_info_msg_2_ を
        # それぞれ緑、黄色、赤で表示する
        [[ -n "$vcs_info_msg_0_" ]] && messages+=( "%F{green}${vcs_info_msg_0_}%f" )
        [[ -n "$vcs_info_msg_1_" ]] && messages+=( "%F{yellow}${vcs_info_msg_1_}%f" )
        [[ -n "$vcs_info_msg_2_" ]] && messages+=( "%F{red}${vcs_info_msg_2_}%f" )

        # 間にスペースを入れて連結する
        prompt="${(j: :)messages}"
fi

RPROMPT="$prompt"
}

add-zsh-hook precmd _update_vcs_info_msg
RPROMPT="%1(v|%F{green}%1v%2v%f|)"
PROMPT='%{[$[32+$RANDOM % 5]m%}%n@%m:%~%%%{[m%}%u '

function rfc(){ command wget -q -O- http://www.ietf.org/rfc/rfc$1.txt | lv }

autoload -Uz url-quote-magic
zle -N self-insert url-quote-magic

source ~/.zsh.d/plugins
