LineLength:
  Enabled: false

MethodLength:
  Enabled: true
  CountComments: false # count full line comments?
  Max: 50

FavorSprintf:
  Enabled: false

MultilineBlocks:
  Enabled: false

AvoidPerlBackrefs:
  Enabled: false

PercentLiterals:
  Enabled: false

BraceAfterPercent:
  Enabled: false
