{:user {:plugins [[cider/cider-nrepl  "0.24.0"]
                  [codox           "0.10.7"]
                  [jonase/eastwood "0.3.11"]
                  [lein-ancient    "0.6.15"]
                  [lein-bikeshed   "0.5.2"]
                  [lein-cljfmt     "0.6.7"]
                  [lein-cloverage  "1.1.2"]
                  [lein-difftest   "2.0.0"]
                  [lein-exec       "0.3.7"]
                  [lein-licenses   "0.2.2"]
                  [lein-localrepo  "0.5.4"]
                  [lein-marginalia "0.9.1"]
                  [lein-kibit      "0.1.8"]
                  [lein-pprint     "1.3.2"]
                  [lein-try        "0.4.3"]
                  [lein-typed      "0.4.6"]
                  [perforate       "0.3.4"]
                  [refactor-nrepl "2.5.0"]]
        :search-page-size 30
        :dependencies  [[org.clojure/tools.namespace "1.0.0"]
                        [im.chit/vinyasa             "0.4.7"]
                        [jonase/kibit                "0.1.8"]
                        [spyscope                    "0.1.6"]]
        :injections  [(require 'spyscope.core)]
        :jvm-opts ["-XX:+TieredCompilation" "-XX:TieredStopAtLevel=1"]}}
