[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['context_filetype.vim', 'denops.vim']
on_event = ['InsertEnter', 'CursorHold']
hook_source = '''
" <TAB>: completion.
inoremap <silent><expr> <TAB>
\ pumvisible() ? '<C-n>' :
\ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
\ '<TAB>' : ddc#map#manual_complete()

" <S-TAB>: completion back.
inoremap <expr><S-TAB>  pumvisible() ? '<C-p>' : '<C-h>'
inoremap <silent><expr> <C-l> ddc#complete_common_string()

call ddc#custom#patch_global(
      \ 'sources', ['around', 'vim-lsp', 'dictionary']
      \ )
call ddc#custom#patch_global('ui', 'native')
call ddc#custom#patch_global('sourceOptions', {
      \ '_': {
      \   'matchers': ['matcher_head'],
      \   'sorters': ['sorter_rank'],
      \ },
      \ 'around': {'mark': 'A'},
      \ 'eskk': {'mark': 'eskk', 'matchers': [], 'sorters': []},
      \ 'necovim': {'mark': 'vim'},
      \ 'vim-lsp': {
      \   'mark': 'lsp',
      \   'forceCompletionPattern': '\.\w*|:\w*|->\w*'},
      \ 'skkeleton': {
      \   'mark': 'skkeleton',
      \   'matchers': ['skkeleton'],
      \   'sorters': [],
      \   },
      \ })

call ddc#enable()
'''

[[plugins]]
repo = 'shun/ddc-vim-lsp'
depends = ["vim-lsp"]
on_source = 'ddc.vim'
