[[plugins]]
repo = 'vim-denops/denops.vim'
hook_source = '''
" let g:denops#server#service#deno_args = get(g:,
" \ 'denops#server#service#deno_args', [
" \ '-q',
" \ '--no-check',
" \ '--unstable',
" \ '-A',
" \ ]) + ['--inspect']
'''

[[plugins]]
repo = 'Shougo/ddc-source-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-zsh'
on_ft = 'zsh'
depends = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_length'
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-dictionary'
on_source = 'ddc.vim'
hook_source = '''
call ddc#custom#patch_global('sourceParams', {
      \ 'dictionary': {'dictPaths': 
      \ [
      \ '/usr/share/dict/words',
      \ ],
      \ 'smartCase': v:true,
      \ }
      \ })
call ddc#custom#patch_global('sourceOptions', {
      \ 'dictionary': {'mark': 'D'},
      \ })
'''

[[plugins]]
repo = 'Shougo/ddc-ui-native'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-inline'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-ui-none'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-cmdline'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-cmdline-history'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-omni'

[[plugins]]
repo = 'matsui54/ddc-buffer'
on_source = 'ddc.vim'
