[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'carlitux/deoplete-ternjs'
on_ft = 'javascript'
do = 'npm install -g tern'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = 'go'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = ['Shougo/context_filetype.vim']
if = "has('nvim')"
on_i = 1
hook_source = '''
let g:deoplete#enable_at_startup = 1
source ~/.vim/my/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'
