# [[plugins]]
# repo = 'ballerina-attic/plugin-vim'
# on_ft = ['bal']

[[plugins]]
repo = 'vim-scripts/a.vim'
on_ft = ['c', 'cpp']
hook_add = '''
let g:alternateSearchPath = 'sfr:../source,sfr:../src,sfr:../include,sfr:../inc,wdr:include/shiguredo/mp4,wdr:src'
let g:alternateRelativeFiles = 0
let g:alternateNoDefaultAlternate = 1
'''

[[plugins]]
repo = 'haruyama/vim-gencode-cpp'
on_ft = ['cpp']
depends = ['a.vim']

[[plugins]]
repo = 'rhysd/vim-clang-format'
on_ft = ['c', 'cpp']
hook_add = '''
let g:clang_format#auto_format = 1
'''

[[plugins]]
repo = 'liquidz/vim-iced'
on_ft = ['clojure']
hook_source = '''
let g:iced_enable_default_key_mappings = v:true
'''

[[plugins]]
repo = 'tpope/vim-fireplace'
on_ft = ['clojure']

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

# [[plugins]]
# repo = 'rhysd/vim-crystal'
# on_ft = ['crystal']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'css']
hook_add = '''
let g:user_emmet_install_global = 0
autocmd FileType html,css EmmetInstall
'''

[[plugins]]
repo = 'aohta/blockdiag.vim',
on_ft = ['diag']

# [[plugins]]
# repo = 'ElmCast/elm-vim'
# on_ft = ['elm']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_source = '''
let g:go_snippet_engine = 'neosnippet'

let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1

let g:go_def_mapping_enabled = 0
let g:go_doc_keywordprg_enabled = 0

let g:go_fmt_command = 'gosimports'
'''

[[plugins]]
repo = 'nbouscal/vim-stylish-haskell'
on_ft = ['haskell']

[[plugins]]
repo = 'b4b4r07/vim-hcl'
on_ft = ['hcl']

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'yuezk/vim-js'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'MaxMEllon/vim-jsx-pretty'
on_ft = ['javascript', 'javascript.jsx', 'javascriptreact', 'tsx', 'typescriptreact']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_add = '''
let g:vim_json_syntax_conceal = 0
'''

# [[plugins]]
# repo = 'zah/nim.vim'
# on_ft = 'nim'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_add = '''
let g:jedi#use_tabs_not_buffers = 1
let g:jedi#popup_select_first = 0
let g:jedi#popup_on_dot = 0
let g:jedi#goto_command = "<leader>d"
let g:jedi#goto_assignments_command = "<leader>g"
let g:jedi#goto_definitions_command = ""
let g:jedi#documentation_command = "K"
let g:jedi#usages_command = "<leader>n"
let g:jedi#rename_command = "<leader>R"
autocmd! FileType python setlocal completeopt-=preview
'''

[[plugins]]
repo = 'python-rope/ropevim'
on_ft = 'python'
hook_add = '''
let ropevim_vim_completion=1
let ropevim_extended_complete=1
let g:ropevim_autoimport_modules = ['os', 'shutil', 'sys', 'time']
'''

# [[plugins]]
# repo = 'purescript-contrib/purescript-vim'
# on_ft = 'purescript'

[[plugins]]
repo = 'tpope/gem-ctags'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-bundler'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rake'
on_ft = ['ruby']

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
hook_source = '''
let g:rustfmt_autosave = 1
let g:rustfmt_command = '$HOME/.cargo/bin/rustfmt'
'''

[[plugins]]
repo = 'haruyama/scheme.vim'
on_ft = ['scheme']

[[plugins]]
repo = 'evanleck/vim-svelte'
on_ft = ['svelte']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = ['typescript']

# [[plugins]]
# repo = 'Quramy/tsuquyomi'
# on_ft = ['typescript']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['vue']

[[plugins]]
repo = 'mrk21/yaml-vim'
on_ft = ['yaml']

[[plugins]]
repo = 'ziglang/zig.vim'
on_ft = ['zig']
