[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim', 'neoyank.vim']
if = '''has('nvim') || (v:version >= 800 && has('python3'))'''
hook_source = '''
source ~/.vim/my/plugins/denite.vim
'''

[[plugins]]
repo = 'Shougo/unite.vim'
depends = ['neomru.vim', 'neoyank.vim']
if   = '''! (has('nvim') || (v:version >= 800 && has('python3')))'''
hook_source = '''
source ~/.vim/my/plugins/unite.vim
'''

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'dsolstad/vim-wombat256i'
hook_add = '''
if !has("gui_running")
  set background=dark
  augroup colorscheme
    autocmd! VimEnter * colorscheme wombat256i
  augroup END
endif
'''

[[plugins]]
repo = 'vim-scripts/AutoTag'

[[plugins]]
repo = 'Shougo/context_filetype.vim'
hook_source = '''
let g:context_filetype#filetypes = {
      \ 'html': [
      \   {
      \     'start' : '^\s*<script type="application/x-go">',
      \     'end' : '^\s*</script>',
      \     'filetype' : 'go',
      \   },
      \   {
      \     'start' : '^\s*<style>',
      \     'end' : '^\s*</style>',
      \     'filetype' : 'css',
      \   },
      \ ]
      \}
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neco-syntax'

[[plugins]]
repo = 'raymond-w-ko/vim-niji'
hook_add = '''
let g:niji_matching_filetypes = ['lisp', 'scheme']
'''

[[plugins]]
repo = 'haruyama/EnhCommentify.vim'

#[[plugins]]
#repo = 'haruyama/vim-matchopen'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
xnoremap <silent> <Leader>a :EasyAlign<cr>
'''

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

# [[plugins]]
# repo = 'rhysd/clever-f.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_linters = {
\   'cpp': ['cc', 'clangd', 'clangtidy', 'cppcheck'],
\   'javascript': ['eslint'],
\   'go': ['go build', 'go vet'],
\   'html': ['alex', 'htmlhint', 'proselint', 'write-good'],
\   'rust': ['cargo', 'rls'],
\}
nnoremap <silent> <leader>an :ALENextWrap<cr>
nnoremap <silent> <leader>ap :ALEPreviousWrap<cr>
let g:ale_go_bingo_executable = 'gopls'
let g:ale_javascript_eslint_suppress_missing_config = 1
let g:ale_python_mypy_options = '--ignore-missing-imports'
'''
# \   'go': ['go build', 'gosimple', 'go vet', 'staticcheck'],

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
let g:quickrun_config = {
\    "octave" : {
\       "command" : "octave",
\       "cmdopt"  : "--silent",
\   },
\    "ceylon" : {
\       "command" : "ceylon",
\       "cmdopt"  : "compile",
\   },
\}
'''

[[plugins]]
repo = 'thinca/vim-template'
hook_add = '''
let g:template_vim_template_dir  = $HOME . '/.vim/template'
let g:template_vim_template_dirs = [$HOME . '/.vim/template']
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'LeafCage/yankround.vim'
hook_add = '''
let g:yankring_history_dir            = $HOME . '/.vim/history'
let g:yankring_manual_clipboard_check = 1

nmap p <Plug>(yankround-p)
nmap P <Plug>(yankround-P)
nmap <C-p> <Plug>(yankround-prev)
nmap <C-n> <Plug>(yankround-next)
let g:yankround_max_history = 50
'''

[[plugins]]
repo = 'haya14busa/is.vim'

[[plugins]]
repo = 'mh21/errormarker.vim'

[[plugins]]
repo = 'guns/vim-sexp'

[[plugins]]
repo = 'tpope/vim-sexp-mappings-for-regular-people'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'rhysd/committia.vim'

# [[plugins]]
# repo = 'majutsushi/tagbar'
# hook_add = '''
# source ~/.vim/my/plugins/tagbar.vim
# '''

[[plugins]]
repo = 'liuchengxu/vista.vim'
hook_add = '''
let g:vista_default_executive = 'lcn'
'''

[[plugins]]
repo = 'janko-m/vim-test'
depends = ['vimproc.vim']
hook_add = '''
nmap <silent> <leader>t :TestNearest<CR>
nmap <silent> <leader>f :TestFile<CR>
nmap <silent> <leader>s :TestSuite<CR>
nmap <silent> <leader>l :TestLast<CR>
nmap <silent> <leader>g :TestVisit<CR>

if has('nvim')
  let g:test#strategy = 'vimproc'
endif

let g:test#python#pytest#options = {
  \ 'nearest': '-v',
  \ 'file':    '-v',
  \ 'suite':   '-v',
\}
let g:test#go#gotest#options = {
  \ 'nearest': '-v',
  \ 'file':    '-v',
  \ 'suite':   '-v',
\}
'''

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'

[[plugins]]
repo = 'osyo-manga/vim-textobj-multitextobj'

[[plugins]]
repo = 'sgur/vim-textobj-parameter'

[[plugins]]
repo = 'farmergreg/vim-lastplace'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = '''!has('nvim') && (v:version >= 800 && has('python3'))'''

[[plugins]]
repo = 'roxma/nvim-yarp'
if = '''!has('nvim') && (v:version >= 800 && has('python3'))'''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = '''
set hidden

let g:LanguageClient_rootMarkers = {
      \ 'clojure': ['project.clj'],
      \ 'go': ['.git', 'go.mod'],
      \ 'purescript': ['bower.json'],
      \ 'rust': ['Cargo.toml'],
      \ }

let g:LanguageClient_serverCommands = {
      \ 'html': [],
      \ 'css': [],
      \ 'clojure': ['bash', '-c', '~/bin/clojure-lsp'],
      \ 'haskell': ['hie-wrapper'],
      \ 'javascript': ['javascript-typescript-stdio'],
      \ 'jsx': ['javascript-typescript-stdio'],
      \ 'javascript.jsx': ['javascript-typescript-stdio'],
      \ 'purescript': ['purescript-language-server', '--stdio'],
      \ 'rust': ['rls'],
      \ 'typescript': ['javascript-typescript-stdio'],
      \ 'typescript.tsx': ['javascript-typescript-stdio'],
      \ 'tsx': ['javascript-typescript-stdio'],
      \ 'vue': ['vls'],
      \ 'go': ['gopls'],
      \ 'python': ['pyls'],
      \ 'c': ['clangd', '-compile-commands-dir=' . getcwd()],
      \ 'cpp': ['clangd', '-compile-commands-dir=' . getcwd()],
      \ }

"       \ 'c': ['ccls'],
"       \ 'cpp': ['ccls'],

nnoremap <F5> :call LanguageClient_contextMenu()<CR>
" Or map each action separately
nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
nnoremap <silent> gd :call LanguageClient#textDocument_definition()<CR>
nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
let g:LanguageClient_diagnosticsEnable = 0
"autocmd BufWritePre *.go :call LanguageClient#textDocument_formatting_sync()
" let g:LanguageClient_loggingLevel = 'INFO'
" let g:LanguageClient_loggingFile = expand('~/.local/share/nvim/LanguageClient.log')
" let g:LanguageClient_serverStderr = expand('~/.local/share/nvim/LanguageServer.log')
'''

[[plugins]]
repo = 'tbodt/deoplete-tabnine'
build = './install.sh'

[[plugins]]
repo = 'iberianpig/tig-explorer.vim'
