[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = ['context_filetype.vim']
if = '''has('nvim') || (v:version >= 800 && has('python3'))'''
on_i = 1
hook_source = '''
let g:deoplete#enable_at_startup = 1
source ~/.vim/my/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'
on_i  = 1
depends = ['vim-lsp', 'deoplete.nvim', 'neosnippet-snippets']


[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-snippets'
on_i  = 1
depends = ['vim-lsp']

[[plugins]]
repo = 'thomasfaingnaert/vim-lsp-neosnippet'
on_i  = 1
depends = ['vim-lsp', 'neosnippet-snippets', 'vim-lsp-snippets']

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c', 'cpp']
depends = ['deoplete.nvim']

[[plugins]]
repo = 'deoplete-plugins/deoplete-jedi'
on_ft = 'python'
