#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/haruyama/.Xmodmap"
export VTE_CJK_WIDTH=auto

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.
xset b off

/usr/bin/unclutter -not QEMU&
#/usr/bin/synergyd
#/usr/bin/synergys -a localhost
/usr/lib/notification-daemon/notification-daemon &
#/usr/lib/x86_64-linux-gnu/mate-notification-daemon/mate-notification-daemon
/usr/bin/spacefm -d &

/usr/bin/xinput --set-prop "Logitech Unifying Device. Wireless PID:1028" "Evdev Middle Button Emulation" 1

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/haruyama/.fluxbox/log"
